### ISSUE TITLE
get_pip synthax error

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [hassony2/obman_render#10]
Hi :) Awesome repo !!

Just a heads up that `get_pip` has been updated on Jan 23rd 2021. The new version uses f-strings and is incompatible with python 3.5 of blender. It will throw a synthax error.

You can revert to the old get_pip by replacing the link in the readme:

```
 wget https://bootstrap.pypa.io/3.4/get-pip.py
```

Cheers,
Thibault

**Comment by JudyYe** [comment]
Hi, 

Amazing repo +1! And thank Thibault for the fix! 
Just to add a comment in Sep 2021 that Thibault's get-pip.py seems 404 now. :/

Since python2 ends its life cycle in 2020, I have to specify pip version < 21.0 for a valid pip upgrade. Otherwise I got syntax [error](https://stackoverflow.com/questions/54915381/will-pip-work-for-python-2-7-after-its-end-of-life-on-1st-jan-2020/54915827)
```
/path/to/benlder/2.78/python/bin/pip3 install --upgrade "pip < 21.0"
```
