### ISSUE TITLE
Weird hand pose

### ISSUE THREAD

**Issue by rbregier** [hassony2/obman_render#2]
Hi Yana,

I am trying to reproduce your results of synthetic data generation, but the renderings I obtain depict very unnatural hand poses such as this one:
![00000009](https://user-images.githubusercontent.com/1822210/68401471-151bc200-017a-11ea-8dbd-4d773038ef1e.jpg)

After the renderings are finished, I can see in the viewer of Blender that there is a MANO hand that is not rendered, but which is in a more natural pose:
![image](https://user-images.githubusercontent.com/1822210/68401514-2a90ec00-017a-11ea-8918-1425a05a1693.png)

After following the instructions in the Readme, here is the list of modifications I had to do in order to be able to run the program:
* Install "sacred" package in the Python distribution of Blender
* Copy in the assets/models folder:
  * MANO models
  * SMPL FBX models downloaded from the "SMPL for MAYA" package (https://smpl.is.tue.mpg.de/downloads)
* Modify assets/textures/shapenet/textures_{train/test/val}.txt and replace "/sequoia/data2/dataset/shapenet/ShapeNetCore.v2" by the path of my own ShapeNet repository for every line.
 
Do you have an idea of what may cause this behavior?

In any case, thanks for sharing your research code. The Readme is very clear and detailed compared to many projects on GitHub.

Best,
Romain

**Comment by hassony2** [comment]
Hi !

Sorry for the late response.
I am not sure what might be causing your problem.
Did you make any modification to the code itself (in which case I could also maybe directly take a look at the code you are using) ?
The error probably comes from [setting the smplh hand pose parameters](https://github.com/hassony2/obman_render/blob/98e88ae749780901a51fae6c78ef17681869af48/blender_grasps.py#L192) and [applying the specific hand pose parameters](https://github.com/hassony2/obman_render/blob/98e88ae749780901a51fae6c78ef17681869af48/obman_render/mesh_manip.py#L182) to the hand.

It looks like when you apply the pose parameters to the hand of the SMPLH model, you don't obtain the same hand as when you apply it to the MANO model. This means that in the way you either load or apply the pose to both models there is a difference.

The things that might cause such behavior could be:
- mismatch between flat_hand_mean as True vs False between MANO and SMPLH (but this looks correct in the github code, e.g. [flat_hand_mean to True](https://github.com/hassony2/obman_render/blob/98e88ae749780901a51fae6c78ef17681869af48/blender_grasps.py#L122)
- SMPLH hand using axis-angles instead of PCA components (but at the same line this looks fine)
- pose parameters applied to the wrong hand --> did you look at the other hand to see in what pose it was ?
- pose parameters not applied at all to SMPLH (this could happen if you are launching the script with different arguments then the ones suggested in the readme)

Let me know if this is of any help, and don't hesitate to give me more information about your issue.

All the best !

Yana

**Comment by rbregier** [comment]
Thanks for your answer,

After triple checking everything, it turns out that I did a silly mistake while modifying paths in the function loading the SMPLH model (smpl_handpca_wrapper.py file, line 85):
I replaced MANO_RIGHT.pkl by MANO_LEFT.pkl  

After fixing it the images are much better:
![00000009](https://user-images.githubusercontent.com/1822210/70629626-93acc900-1c2a-11ea-820d-085b536a6988.jpg)

Sorry for bothering you for this, and thanks for your time.
Romain
